### ISSUE TITLE
Cookie consent links to wrong page

### ISSUE THREAD

**Issue by IsakSundeSingh** [mellet/csgonades-client#18]
The cookie consent bar links to the wrong page for the privacy policy.
https://github.com/mellet/csgonades-client/blob/7fd7343256844b9c98d6fa83e437b65d6cac9d88/src/common/CookieConsent.tsx#L41

It should be
```tsx
 <a href="/privacypolicy">cookies</a> for analytics and advertising. 
```

**Comment by mellet** [comment]
Thanks for reporting this issue.
It has now been fixed by one of our developers.
