### ISSUE TITLE
Typo in READ.md

### ISSUE THREAD

**Issue by Jwright707** [mellet/csgonades-client#35]
Currently -> Sarting dev server
Desired Text -> Starting dev server

I would like to work on this if this is a valid issue @mellet . 
Thank you

**Comment by f4bio** [comment]
I'm pretty sure @mellet is glad about every contribution (open source, baby! 🏆 )

**Comment by Jwright707** [comment]
Thank you @f4bio . I'll make that edit and make a PR @mellet
